name: Scraper Partidos HA Basket

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar Chrome
        run: npx puppeteer browsers install chrome

      - name: Ejecutar scraper
        run: node scraper.js

      - name: Subir debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            debug.png
            public/partidos.json
          if-no-files-found: warn
